baseURL: https://example.com
title: Здравствуйте, я Алексей Темкин
languageCode: en-us
theme: hugo-theme-hello-friend-ng
PygmentsCodeFences: yes
PygmentsStyle: monokai
paginate: 10
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
buildDrafts: no
buildFuture: no
buildExpired: no
canonifyURLs: yes
enableRobotsTXT: yes
enableGitInfo: no
enableEmoji: yes
enableMissingTranslationPlaceholders: no
disableRSS: no
disableSitemap: no
disable404: no
disableHugoGeneratorInject: no
permalinks:
  posts: /posts/:year/:month/:title/
author:
  name: Алексей Темкин
blackfriday:
  hrefTargetBlank: yes
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  customCSS: []
  customJS: []
  dateform: Jan 2, 2006
  dateformNum: '2021-05-04'
  dateformNumTime: 2021-05-04 15:04
  dateformShort: Jan 2
  description: Nice theme for homepages and blogs
  disableReadOtherPosts: no
  enableSharingButtons: yes
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  homeSubtitle: Это мой сайт с использованием тем HUGO и blogdown
  images: ''
  justifyContent: no
  keywords: ''
  logo:
    logoHomeLink: /
    logoMark: '>'
    logoText: $ cd /главная/
  social:
    - name: twitter
      url: https://twitter.com/
    - name: email
      url: mailto:nobody@example.com
    - name: github
      url: https://github.com/
    - name: linkedin
      url: https://www.linkedin.com/
    - name: stackoverflow
      url: https://www.stackoverflow.com/
languages:
  en:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Hello Friend NG Theme
    weight: 1
  fr:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Hello Friend NG Theme
    weight: 2
menu:
  main:
    - identifier: about
      name: Обо мне
      url: about/
    - identifier: posts
      name: Посты
      url: posts/
    - identifier: NewPage
      name: Новая страница
      url: newpage/
    - identifier: YouTube
      name: YouTube
      url: youtube/
